version: '3'
services:

  db:
    image: postgres:10-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:5.0.7

  api:
    depends_on:
      - db
      - redis
    build: ./api
    container_name: api
    entrypoint: ["/api/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    volumes:
      - ./api:/api
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db

  sidekiq:
    build: ./api
    depends_on:
      - api      
      - db
      - redis
    volumes:
      - ./api:/api
    entrypoint: ["/api/sidekiq-entrypoint.sh"]
